(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (add-to-list 'meow-mode-state-list '(lsp-bridge-ref-mode . motion))
  (meow-motion-overwrite-define-key
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("/" . meow-keypad-describe-key)
   '("a" . ignore)
   '("b" . consult-buffer)
   '("c" . ignore)
   '("d" . diff-hl-show-hunk)
   '("e" . lsp-bridge-diagnostic-list)
   '("o" . ace-select-window)
   '("k".  delete-window)
   '("p" . "C-x p")
   '("r" . delete-other-windows)
   '("s" . save-buffer)
   '("v" . magit)
   '("w" . persp-switch)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . ignore)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("C" . ignore)
   '("d" . meow-kill)
   '("D" . lsp-bridge-find-def)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("F" . ignore)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . lsp-bridge-find-impl)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("M" . ignore)
   '("n" . ignore)
   '("N" . ignore)
   '("o" . meow-open-below)
   '("O" . meow-open-above)
   '("p" . meow-yank)
   '("P" . meow-yank-pop)
   '("q" . meow-quit)
   '("Q" . ignore)
   '("r" . meow-replace)
   '("R" . lsp-bridge-find-references)
   '("s" . consult-line)
   '("S" . ignore)
   '("t" . meow-till)
   '("T" . ignore)
   '("u" . meow-undo)
   '("U" . ignore)
   '("v" . scroll-up-command)
   '("V" . scroll-down-command)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line-expand)
   '("X" . ignore)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("Z" . ignore)
   '("/" . avy-goto-char-timer)
   '("<" . xref-go-back)
   '(">" . xref-go-forward)
   '("'" . meow-replace)
   '("<escape>" . ignore)))

(use-package meow
  :config
  (setq meow-expand-hint-counts
	'((line . 30)
	  (find . 30)
	  (till . 30)))
  (meow-setup)
  (meow-global-mode)
  )
(provide 'init-meow)
